"""add skill in task

Revision ID: 6078a1e4f280
Revises: 2ecf95cbda9d
Create Date: 2026-03-18 06:41:32.388766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6078a1e4f280'
down_revision: Union[str, Sequence[str], None] = '2ecf95cbda9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('skill', sa.Enum('frontend', 'backend', 'fullstack', 'devops', 'qa', 'design', name='skillenum'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'skill')
    # ### end Alembic commands ###
