"""skill null true

Revision ID: 76388985ed1d
Revises: 7d3aed2b04ff
Create Date: 2026-03-16 21:43:13.815312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '76388985ed1d'
down_revision: Union[str, Sequence[str], None] = '7d3aed2b04ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'skill',
               existing_type=postgresql.ENUM('frontend', 'backend', 'fullstack', 'devops', 'qa', 'design', name='skillenum'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'skill',
               existing_type=postgresql.ENUM('frontend', 'backend', 'fullstack', 'devops', 'qa', 'design', name='skillenum'),
               nullable=False)
    # ### end Alembic commands ###
