"""skill nullable true

Revision ID: 7d3aed2b04ff
Revises: 733c490c7445
Create Date: 2026-03-16 20:27:12.573542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d3aed2b04ff'
down_revision: Union[str, Sequence[str], None] = '733c490c7445'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'skill',
               existing_type=postgresql.ENUM('frontend', 'backend', 'fullstack', 'devops', 'qa', 'design', name='skillenum'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'skill',
               existing_type=postgresql.ENUM('frontend', 'backend', 'fullstack', 'devops', 'qa', 'design', name='skillenum'),
               nullable=True)
    # ### end Alembic commands ###
