"""add deadline reminder flag

Revision ID: 85ef772a1a01
Revises: c2a37102befc
Create Date: 2026-03-15 00:20:27.479518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85ef772a1a01'
down_revision: Union[str, Sequence[str], None] = 'c2a37102befc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('deadline_reminder_sent', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'deadline_reminder_sent')
    # ### end Alembic commands ###
