"""add column

Revision ID: b19464117148
Revises: fdd0e32f87f4
Create Date: 2026-03-29 06:47:24.014842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b19464117148'
down_revision: Union[str, Sequence[str], None] = 'fdd0e32f87f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reset_password', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_reset_password_email'), table_name='reset_password')
    op.create_foreign_key(None, 'reset_password', 'users', ['user_id'], ['id'])
    op.drop_column('reset_password', 'email')
    op.drop_column('reset_password', 'company_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reset_password', sa.Column('company_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('reset_password', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'reset_password', type_='foreignkey')
    op.create_index(op.f('ix_reset_password_email'), 'reset_password', ['email'], unique=False)
    op.drop_column('reset_password', 'user_id')
    # ### end Alembic commands ###
