"""add company_name column in users

Revision ID: c1b53dbecbc5
Revises: 1aabff0b9101
Create Date: 2026-03-24 02:00:19.536959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1b53dbecbc5'
down_revision: Union[str, Sequence[str], None] = '1aabff0b9101'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('company_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'company_name')
    # ### end Alembic commands ###
