"""add task deadline

Revision ID: c2ecb3cd49b7
Revises: 85ef772a1a01
Create Date: 2026-03-15 00:38:47.169870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2ecb3cd49b7'
down_revision: Union[str, Sequence[str], None] = '85ef772a1a01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('deadline', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'deadline')
    # ### end Alembic commands ###
