"""add otp system

Revision ID: e3362af16283
Revises: b19464117148
Create Date: 2026-03-29 07:50:32.911584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3362af16283'
down_revision: Union[str, Sequence[str], None] = 'b19464117148'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reset_password', sa.Column('otp', sa.String(), nullable=True))
    op.add_column('reset_password', sa.Column('is_used', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('reset_password_token_key'), 'reset_password', type_='unique')
    op.drop_column('reset_password', 'token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reset_password', sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('reset_password_token_key'), 'reset_password', ['token'], postgresql_nulls_not_distinct=False)
    op.drop_column('reset_password', 'is_used')
    op.drop_column('reset_password', 'otp')
    # ### end Alembic commands ###
